# 00_PyTorch Fundamentals

In [1]:
# Install torch module
%pip install torch

import torch
print(torch.__version__)

Note: you may need to restart the kernel to use updated packages.
2.5.1+cpu


In [2]:
import torch

## Intro to Tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
#MATRIX 
MATRIX = torch.tensor([[[[1, 1, 1],
                         [2, 2, 2],
                         [3, 3, 3],
                         [4, 4, 4]]],
                         [[[1, 1, 2],
                         [2, 2, 2],
                         [3, 3, 3],
                         [4, 4, 4]]]])
MATRIX

tensor([[[[1, 1, 1],
          [2, 2, 2],
          [3, 3, 3],
          [4, 4, 4]]],


        [[[1, 1, 2],
          [2, 2, 2],
          [3, 3, 3],
          [4, 4, 4]]]])

In [8]:
MATRIX.ndim # dimensi adalah banyaknya square brackets di dalam tensor

4

In [9]:
MATRIX.shape # shape adalah urutan banyaknya elemen pada sqb terluar ke terdalam

torch.Size([2, 1, 4, 3])

### Random Tensors

In [10]:
random_tensor = torch.rand(10, 10)
random_tensor

tensor([[0.4599, 0.5130, 0.4092, 0.0238, 0.8088, 0.0241, 0.4793, 0.9092, 0.8782,
         0.7583],
        [0.7279, 0.8827, 0.4762, 0.7679, 0.0282, 0.4664, 0.7464, 0.0771, 0.5633,
         0.2996],
        [0.9853, 0.2380, 0.2530, 0.2884, 0.8082, 0.3791, 0.9140, 0.4900, 0.0996,
         0.4939],
        [0.0147, 0.2076, 0.7268, 0.8152, 0.4270, 0.1592, 0.2757, 0.3615, 0.0758,
         0.2183],
        [0.7000, 0.4233, 0.5144, 0.0555, 0.9692, 0.7803, 0.6508, 0.5954, 0.4827,
         0.2271],
        [0.9394, 0.6983, 0.1233, 0.7252, 0.5653, 0.7393, 0.2905, 0.7510, 0.6818,
         0.1631],
        [0.5807, 0.5395, 0.1266, 0.6156, 0.1072, 0.1880, 0.2113, 0.9635, 0.1183,
         0.3580],
        [0.7624, 0.1775, 0.6023, 0.9845, 0.1116, 0.2217, 0.7251, 0.8419, 0.0575,
         0.3422],
        [0.8580, 0.2866, 0.1647, 0.3779, 0.6109, 0.9863, 0.3853, 0.8145, 0.9259,
         0.2271],
        [0.3514, 0.9662, 0.1609, 0.9573, 0.2277, 0.6088, 0.0865, 0.1452, 0.6194,
         0.5696]])

In [11]:
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channel
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones tensor

In [12]:
ones = torch.ones(3, 4)
ones * torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Tensor Datatype

**Note** : 3 error yang akan sering ditemui ketika belajar PyTorch & Deep Learning
1. tipe data tensor yang salah
2. bentuk tensor yang tidak benar
3. tensors not in the right device


In [13]:
# float32 tensors
float_32_tensor =  torch.tensor([3.0, 6.0, 4.0], 
                                dtype=None, # default is torch.float32 
                                device=None, # what device the tensor is on
                                requires_grad=False) # whether or not to track gradients with this tensor
float_32_tensor.dtype

torch.float32

In [14]:
tensor_64_int = torch.tensor([3, 6, 4], dtype=torch.int64)

multiply = float_32_tensor * tensor_64_int
multiply

tensor([ 9., 36., 16.])

- tensor dengan tipe data yang berbeda bisa dioperasikan, namun hasilnya akan mengikuti tipe data yang lebih tinggi
- untuk mengetahui type data tensor, kita bisa menggunakan `.dtype`
- untuk mengetahui device apa yang digunakan untuk mengoperasikan tensor, kita bisa menggunakana `.device`
- untuk mengetahui shape dari tensor, kita bisa menggunakan `.shape`



In [15]:
tensor_64_int.device

device(type='cpu')

In [16]:
rand_tensor = torch.rand(5, 5);
print(rand_tensor)
print(f"The shape of the tensor is : {rand_tensor.shape}")
print(f"The dtype of the tensor is a : {rand_tensor.dtype}")
print(f"The device the tensor executed is on : {rand_tensor.device}")


tensor([[0.0367, 0.5030, 0.6723, 0.3314, 0.6376],
        [0.9094, 0.7945, 0.7487, 0.6407, 0.3068],
        [0.3123, 0.9125, 0.1996, 0.3334, 0.8196],
        [0.3222, 0.4514, 0.4520, 0.7790, 0.3495],
        [0.7382, 0.1261, 0.0213, 0.6640, 0.9417]])
The shape of the tensor is : torch.Size([5, 5])
The dtype of the tensor is a : torch.float32
The device the tensor executed is on : cpu


### Tensor Manipulation

Tensor operations, include :
1. addition
2. subtraction
3. multiplication (elemen wise)
4. division 
5. matrix multiplication

In [17]:
# create a tensor
num_tensor = torch.rand(3, 3)
num_tensor

tensor([[0.1645, 0.9184, 0.0251],
        [0.3773, 0.6589, 0.9662],
        [0.4900, 0.9818, 0.4260]])

In [18]:
# membuat tensor berada dalam rentang 0-9
num_tensor *= 10
num_tensor

tensor([[1.6449, 9.1845, 0.2507],
        [3.7735, 6.5887, 9.6622],
        [4.8997, 9.8176, 4.2598]])

In [19]:

# menambahkan angka ke dalam tensor
num_tensor + 1

tensor([[ 2.6449, 10.1845,  1.2507],
        [ 4.7735,  7.5887, 10.6622],
        [ 5.8997, 10.8176,  5.2598]])

In [20]:
# menambahkan tensor suatu bilangan
num_tensor + 1

tensor([[ 2.6449, 10.1845,  1.2507],
        [ 4.7735,  7.5887, 10.6622],
        [ 5.8997, 10.8176,  5.2598]])

In [21]:
# mengurangi tensor suatu bilangan
num_tensor - 1

tensor([[ 0.6449,  8.1845, -0.7493],
        [ 2.7735,  5.5887,  8.6622],
        [ 3.8997,  8.8176,  3.2598]])

#### Tensor Multiplication
1. Element-wise mul
2. Matrix mul

In [22]:
int_tensor = (torch.rand(3, 3)*10).to(torch.int64)
int_tensor

tensor([[4, 9, 6],
        [4, 7, 4],
        [4, 9, 0]])

In [23]:
# Element-wise multiplication
int_tensor * 10


tensor([[40, 90, 60],
        [40, 70, 40],
        [40, 90,  0]])

Menggunakan looping manual tanpa bantuan PyTorch


In [24]:
%%time
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([2, 3, 4])
total = 0

for i in range(len(tensor1)):
    total += tensor1[i] * tensor2[i]
print(total)

tensor(20)
CPU times: total: 0 ns
Wall time: 1.99 ms


Menggunakan framework PyTorch


In [25]:
%%time
print(torch.matmul(tensor1, tensor2))

tensor(20)
CPU times: total: 0 ns
Wall time: 5 ms


In [26]:
tensor_A = torch.tensor([[1, 2],
                          [3, 4],
                          [5, 6]])
tensor_B = torch.tensor([[7, 10],
                          [8, 11],
                          [9, 12]])
print(f"shape of tensor A is {tensor_A.shape} and shape of tensor B is {tensor_B.shape}")

shape of tensor A is torch.Size([3, 2]) and shape of tensor B is torch.Size([3, 2])


In [27]:
# matrix multiplication     
AxB = torch.mm(tensor_A, tensor_B.T)
AxB, AxB.shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

#### Tensor Aggregation 
Finding min, max, mean, sum, etc

In [28]:
X = torch.arange(0, 100, 10)
X = X.to(torch.float32)
X

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [29]:
torch.min(X), torch.max(X), torch.mean(X)

(tensor(0.), tensor(90.), tensor(45.))

In [30]:
# find the index of the max value
torch.argmax(X), torch.argmin(X)

(tensor(9), tensor(0))

### Reshaping, stacking, squeezing, and unsqueezing

* Reshaping - reshape an input tensor to a defined shape
* View 
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimension from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input dimension permuted(swapped) in a certain way

In [31]:
# Reshape
tensor_A = torch.arange(1,13, 1);
tensor_A, tensor_A.size()

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [32]:
tensor_A.reshape(3, 4), tensor_A.reshape(2, 6)


(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]]))

In [33]:
# Add extra dimension
A_reshaped = tensor_A.reshape(3, 4)
A_reshaped, A_reshaped.shape, A_reshaped.dim()

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]),
 2)

#### View


In [34]:
X = torch.arange(1, 10, 1)
Z = X.view(1, 9)
Z, Z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [35]:
Z[:, 0] = 5
Z, X

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

#### Squeeze and Unsqueeze

In [36]:
# torch.squeeze removes all single dimension from a target tensor
# membuat tensor
X = torch.arange(1, 10, 1)
X_reshaped = X.reshape(1, 9)

# melihat dimensi
print(f"ini adalah tensor awal : {X_reshaped}")
print(f"ukurannya adalah {X_reshaped.shape}")

# menampilkan dimensi akhir
X_squeezed = X_reshaped.squeeze()
print(f"ini adalah tensor hasil squeezing {X_squeezed}")
print(f"ukurannya adalah {X_squeezed.shape}")

ini adalah tensor awal : tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
ukurannya adalah torch.Size([1, 9])
ini adalah tensor hasil squeezing tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
ukurannya adalah torch.Size([9])


In [37]:
# torch.unsquezee() - add a single dimension to a target tensor

# melihat dimensi
print(f"ini adalah tensor awal : {X_squeezed}")
print(f"ukurannya adalah : {X_squeezed.shape}")

X_unsqueezed = X_squeezed.unsqueeze(0)
print(f"ini adalah tensor hasil unsqueeze {X_unsqueezed}")
print(f"ukurannya adalah : {X_unsqueezed.shape}")


ini adalah tensor awal : tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
ukurannya adalah : torch.Size([9])
ini adalah tensor hasil unsqueeze tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
ukurannya adalah : torch.Size([1, 9])


#### Tensor Permutation
Fungsi utama : mengubah urutan dimensi yang dimiliki tensor

**note** : permutasi tensor adalah view dari tensor asal, artinya mengubah tensor hasil permutasi juga mengubah tensor asal karena mereka berbagi alamat memori yang sama

In [38]:
x_original = torch.rand(size=(224, 224, 3)) # height, width, color channel
print(f"ini adalah tensor awal {x_original}")
print(f"bentuknya adalah : {x_original.shape}")

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)
print(f"ini adalah tensor permuted {x_permuted}")
print(f"bentuknya adalah : {x_permuted.shape}")


ini adalah tensor awal tensor([[[0.0135, 0.5301, 0.2751],
         [0.9390, 0.5017, 0.3684],
         [0.8290, 0.7306, 0.3658],
         ...,
         [0.7221, 0.7464, 0.8232],
         [0.7700, 0.9480, 0.2787],
         [0.5450, 0.6528, 0.9289]],

        [[0.7770, 0.1317, 0.4737],
         [0.0543, 0.2480, 0.6150],
         [0.0675, 0.7922, 0.7423],
         ...,
         [0.1988, 0.8924, 0.2050],
         [0.0795, 0.2429, 0.1076],
         [0.5273, 0.6303, 0.9030]],

        [[0.7372, 0.3746, 0.1183],
         [0.9346, 0.7384, 0.1769],
         [0.3103, 0.2006, 0.0570],
         ...,
         [0.3443, 0.4263, 0.5726],
         [0.8637, 0.5003, 0.7419],
         [0.2029, 0.8538, 0.3756]],

        ...,

        [[0.8097, 0.8114, 0.9682],
         [0.8678, 0.4224, 0.7170],
         [0.6821, 0.3761, 0.4693],
         ...,
         [0.7239, 0.6189, 0.7925],
         [0.7492, 0.4488, 0.4851],
         [0.0109, 0.5325, 0.3658]],

        [[0.0864, 0.6812, 0.6426],
         [0.8776, 0.9161

In [39]:
# bukti bahwa keduanya berbagi alamat memori yang sama
x_original[0, 0, 0] = 12345
x_original[0, 0, 0], x_permuted[0, 0, 0]    

(tensor(12345.), tensor(12345.))

### Indexing and Slicing


In [40]:
# creating a tensor
x = torch.tensor([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]])
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [41]:
x[:, :, 2] # all rows, all columns, index 2

tensor([[3, 6, 9]])

In [42]:
x[:, 2, 1]

tensor([8])

In [43]:
x[:, 1, 2]

tensor([6])

### Tensor and NumPy library



In [44]:
# numpy array to tensor 
import torch
import numpy as np

array = np.arange(1.0, 8.0, 1) # dtype : float64
array = array.astype(np.float32) 
tensor = torch.from_numpy(array) 
tensor, tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [45]:
np_array = tensor.numpy()
np_array, np_array.dtype

(array([1., 2., 3., 4., 5., 6., 7.], dtype=float32), dtype('float32'))

### Reproducibility


Ketika kita ingin membuat tensor weight awal suatu neural network, kita mengaturnya dengan angka acak. Namun,tujuan penelitian mengharuskan angka2 acak itu bisa digunakan berulang2 sehingga peneliti2 lain bisa menghasilkan hasil yang serupa atau mendekati serupa

Seed hadir sebagai angka yang akan diolah oleh algoritma pengacakan untuk menghasilkan angka acak awal. Angka acak awal ini akan digunakan untuk mengenerate angka acak selanjutnya, secara berantai.

In [47]:
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

# Generate the first tensors
random_tensor_A = torch.rand(5, 5)

# Set the random seed again. 
# This is important because the value of random_seed changes each time a new random number is generated
torch.manual_seed(RANDOM_SEED)

# Generate the second tensor
random_tensor_B = torch.rand(5, 5)

# Print the tensors
print(f"Tensor A : {random_tensor_A}")
print(f"Tensor B : {random_tensor_B}")
print("Does tensor A and B equal?", torch.equal(random_tensor_A, random_tensor_B))

Tensor A : tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317, 0.1053]])
Tensor B : tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317, 0.1053]])
Does tensor A and B equal? True
